INSERT INTO curso (nombre, duracion, precio) VALUES ('Curso JAVA', 120, 2000.00)
INSERT INTO curso (nombre, duracion, precio) VALUES ('Curso Python', 100, 1800.00)
INSERT INTO curso (nombre, duracion, precio) VALUES ('Curso HTML y CSS', 60, 1500.00)
INSERT INTO curso (nombre, duracion, precio) VALUES ('Curso JavaScript', 80, 1700.00)
INSERT INTO curso (nombre, duracion, precio) VALUES ('Curso SQL', 50, 1300.00)
INSERT INTO curso (nombre, duracion, precio) VALUES ('Curso C++', 110, 2100.00)
INSERT INTO curso (nombre, duracion, precio) VALUES ('Curso Data Science', 150, 2500.00)
INSERT INTO curso (nombre, duracion, precio) VALUES ('Curso Machine Learning', 140, 2700.00)
INSERT INTO curso (nombre, duracion, precio) VALUES ('Curso Desarrollo Web', 90, 1900.00)
INSERT INTO curso (nombre, duracion, precio) VALUES ('Curso React', 70, 1600.00)
INSERT INTO curso (nombre, duracion, precio) VALUES ('Curso Angular', 80, 1650.00)
INSERT INTO curso (nombre, duracion, precio) VALUES ('Curso Node.js', 85, 1750.00)
INSERT INTO curso (nombre, duracion, precio) VALUES ('Curso PHP', 75, 1550.00)
INSERT INTO curso (nombre, duracion, precio) VALUES ('Curso Ruby on Rails', 95, 2000.00)
INSERT INTO curso (nombre, duracion, precio) VALUES ('Curso DevOps', 100, 2200.00)
INSERT INTO curso (nombre, duracion, precio) VALUES ('Curso C#', 110, 2050.00)
INSERT INTO curso (nombre, duracion, precio) VALUES ('Curso Swift', 95, 2000.00)
INSERT INTO curso (nombre, duracion, precio) VALUES ('Curso Kotlin', 90, 1950.00)
INSERT INTO curso (nombre, duracion, precio) VALUES ('Curso Cloud Computing', 130, 2400.00)
INSERT INTO curso (nombre, duracion, precio) VALUES ('Curso Cyber Security', 120, 2500.00)
INSERT INTO curso (nombre, duracion, precio) VALUES ('Curso Blockchain', 140, 2800.00)
INSERT INTO curso (nombre, duracion, precio) VALUES ('Curso Big Data', 150, 2600.00)
INSERT INTO curso (nombre, duracion, precio) VALUES ('Curso Artificial Intelligence', 160, 3000.00)
INSERT INTO curso (nombre, duracion, precio) VALUES ('Curso UI/UX Design', 80, 1800.00)
INSERT INTO curso (nombre, duracion, precio) VALUES ('Curso Agile Methodologies', 60, 1500.00)